### ISSUE TITLE
Option to write to memory stream instead of toFile

### ISSUE THREAD

**Issue by toooo** [LoicMahieu/PDFKitJS#1]
Hi,

Im sending .pdf as email attachments and was wondering if it would be possible to circumvent writing toFile and then reading that file as data to encode with base64.

`var attachment = new Buffer(data).toString('base64');`

http://codewinds.com/blog/2013-08-19-nodejs-writable-streams.html#creating_writable_memory_stream

I ve seen in tests that u started to implement toStream function, will there be that option?

**Comment by LoicMahieu** [comment]
Hi,
At this time, no. You could not get a stream of the generated PDF. Really hacky solution would be to write to a file and open a read stream on it but it is a really bad solution.

Instead of that, I recommend you to use the excellent [`wkhtmltopdf`](https://github.com/devongovett/node-wkhtmltopdf) from devongovett which allows you to use stream as primary interface. In fact, I will write a deprecated warning for this module.
